version: "3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpachato
    ports:
      - 3307:3306
    volumes:
      - db:/data/db




  spring-app:
    depends_on:
      - mysqldb
    image: wajdi03/storewithspring:latest
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - 8089:8089

    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  angular-app:
    #The docker file in FE, builds and provides the docker image.
    image: wajdi03/storewithangular:latest
    depends_on:
      - spring-app
    ports:
      - 4200:4200

volumes:
  db:


#  sonarqube:
#    image: sonarqube:8.9.7-community
#    ports:
#      - "9000:9000"
#      - "9092:9092"
#
#  nexus:
#    image: sonartype/nexus3
#    ports:
#      - "8081:8081"


